package com.ibm.cics.sample.jaxrs;
import com.ibm.jzos.fields.*;

// Generated by com.ibm.jzos.recordgen.cobol.RecordClassGenerator on Wed Mar 16 01:44:51 GMT+09:00 2011

public class Catalog {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 01 WS-CAT-ITEM. </pre> */
	public static final int WS_CAT_ITEM_len = 80; 

	/** <pre>
	         05 WS-ITEM-REF          PIC 9(4). </pre> */
	protected static ExternalDecimalAsIntField WS_ITEM_REF = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	         05 WS-DESCRIPTION       PIC X(40). </pre> */
	protected static StringField WS_DESCRIPTION = factory.getStringField(40);

	/** <pre>
	         05 WS-DEPARTMENT        PIC 9(3). </pre> */
	protected static ExternalDecimalAsIntField WS_DEPARTMENT = factory.getExternalDecimalAsIntField(3, false, false, false, false);

	/** <pre>
	         05 WS-COST              PIC ZZZ.99. </pre> */
	protected static StringField WS_COST = factory.getStringField(6);

	/** <pre>
	         05 WS-IN-STOCK          PIC 9(4). </pre> */
	protected static ExternalDecimalAsIntField WS_IN_STOCK = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	         05 WS-ON-ORDER          PIC 9(3). </pre> */
	protected static ExternalDecimalAsIntField WS_ON_ORDER = factory.getExternalDecimalAsIntField(3, false, false, false, false);

	/** <pre>
	         05 FILLER               PIC X(20). </pre> */
	protected static StringField FILLER_1 = factory.getStringField(20);

	protected byte[] _byteBuffer;


	public Catalog (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public Catalog () {
		this._byteBuffer = new byte[WS_CAT_ITEM_len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public int getWsItemRef() {
		return WS_ITEM_REF.getInt(_byteBuffer);
	}

	public void setWsItemRef(int wsItemRef) {
		WS_ITEM_REF.putInt(wsItemRef, _byteBuffer);
	}

	public String getWsDescription() {
		return WS_DESCRIPTION.getString(_byteBuffer);
	}

	public void setWsDescription(String wsDescription) {
		WS_DESCRIPTION.putString(wsDescription, _byteBuffer);
	}

	public int getWsDepartment() {
		return WS_DEPARTMENT.getInt(_byteBuffer);
	}

	public void setWsDepartment(int wsDepartment) {
		WS_DEPARTMENT.putInt(wsDepartment, _byteBuffer);
	}

	public String getWsCost() {
		return WS_COST.getString(_byteBuffer);
	}

	public void setWsCost(String wsCost) {
		WS_COST.putString(wsCost, _byteBuffer);
	}

	public int getWsInStock() {
		return WS_IN_STOCK.getInt(_byteBuffer);
	}

	public void setWsInStock(int wsInStock) {
		WS_IN_STOCK.putInt(wsInStock, _byteBuffer);
	}

	public int getWsOnOrder() {
		return WS_ON_ORDER.getInt(_byteBuffer);
	}

	public void setWsOnOrder(int wsOnOrder) {
		WS_ON_ORDER.putInt(wsOnOrder, _byteBuffer);
	}

	public String getFiller_1() {
		return FILLER_1.getString(_byteBuffer);
	}

	public void setFiller_1(String filler_1) {
		FILLER_1.putString(filler_1, _byteBuffer);
	}

}
